### PR TITLE
PSPF_PLAYERTRANSLATED fixes to the fists, kick combo fix with the Chainsaw, and text for casings options

### PR DESCRIPTION
**Pull request by JMartinez9820**
Added PSPF_PLAYERTRANSLATED false flags to the punching animation actors to prevent an issue with the PSPF_PLAYERTRANSLATED flag being forced on the fists when doing fist and kicking combos at the same time.

Update 3/22/2020: Restored the double middle finger melee taunt when you use the fists

### CODE REVIEW

**Comment by JMartinez9820** [comment]
New change. Fixed the player color not showing when doing the kick combos with the chainsaw.

**Comment by JMartinez9820** [comment]
New change today. Added description text to the Max Casings option, and properly named the option in Nash Gore settings.

**Comment by JMartinez9820** [comment]
Closing pull request until further notice and when a code cleanup is complete.

**Comment by JMartinez9820** [comment]
Ugh, I feel so dumb for closing this PR while the other ones were merged. I was waiting for a code clean after it was announced, it looks like I made another idiotic mistake. I feel like hurting myself now.  This may also be the last PR I might make for now, since I'm considering abandoning future development until I finish my college semester. College and the COVID-19 outbreak is seriously putting a toll on my role as a developer here.

**Comment by goldenmob72** [comment]
@JMartinez9820 It's not a big deal. We all make mistakes, and not everyone is perfect or don't know things Ahead of time.

**Comment by JMartinez9820** [comment]
Update to my pull request. I fixed a new major issue introduced with the newest commit, which prevented the camera from going back to first person, player sprite disappearance and prevented the player from using weapons after performing the head rip fatality on the Bull Demon (regular Demon).

**Pull request merged**
