### PR TITLE
Basic Full Screen HUD

### PR DESCRIPTION
**Pull request by cemtex-tk**
Basic full screen hud and graphics for PB3.  Very basic and only tends to items already written.  All written in sbarinfo with a font and text color added.

Please let me know if any major problems arise and if any colors should be changed.

### CODE REVIEW

**Comment by vidaritos** [comment]
Screenshot_Doom_20201001_124645
I tried messing around with the scaling options, but it never got any better.

I attached my settings in case I need to change anything for it to work
<details>
<summary>click to expand settings</summary>
[GlobalSettings]
I_FriendlyWindowTitle=1
adl_bank=14
adl_chips_count=6
adl_custom_bank=
adl_emulator_id=0
adl_fullpan=true
adl_run_at_pcm_rate=false
adl_use_custom_bank=false
adl_volume_model=3
autoloadbrightmaps=false
autoloadlights=false
autosavecount=4
autosavenum=0
chase_dist=90
chase_height=-8
cl_capfps=false
cl_defaultconfiguration=2
cl_noprediction=false
cl_oldfreelooklimit=false
cl_predict_lerpscale=0.05000000074505806
cl_predict_lerpthreshold=2
cl_predict_specials=true
cl_run=true
cl_waitforsave=true
con_buffersize=-1
con_ctrl_d=
con_notifylines=4
defaultiwad=DOOM 2: Hell on Earth
demo_compress=true
developer=0
disableautoload=false
disableautosave=0
enablescriptscreenshot=false
fluid_chorus=false
fluid_chorus_depth=8
fluid_chorus_level=1
fluid_chorus_speed=0.30000001192092896
fluid_chorus_type=0
fluid_chorus_voices=3
fluid_gain=0.5
fluid_interp=1
fluid_lib=
fluid_patchset=gzdoom
fluid_reverb=false
fluid_reverb_damping=0.23000000417232513
fluid_reverb_level=0.5699999928474426
fluid_reverb_roomsize=0.6100000143051147
fluid_reverb_width=0.7599999904632568
fluid_samplerate=0
fluid_threads=1
fluid_voices=128
freelook=true
gl_billboard_faces_camera=false
gl_billboard_mode=0
gl_billboard_particles=true
gl_cachenodes=true
gl_cachetime=0.6000000238418579
gl_debug_breakpoint=false
gl_debug_level=0
gl_distfog=70
gl_dither_bpc=0
gl_enhanced_nv_stealth=3
gl_finishbeforeswap=false
gl_fxaa=0
gl_lens=false
gl_lens_chromatic=1.1200000047683716
gl_lens_k=-0.11999999731779099
gl_lens_kcube=0.10000000149011612
gl_light_particles=true
gl_light_shadowmap=false
gl_light_sprites=true
gl_lights=true
gl_mask_sprite_threshold=0.5
gl_mask_threshold=0.5
gl_mirror_envmap=true
gl_multisample=1
gl_multithread=true
gl_no_skyclear=false
gl_particles_style=2
gl_plane_reflection=true
gl_render_precise=false
gl_satformula=1
gl_seamless=false
gl_shadowmap_filter=1
gl_shadowmap_quality=512
gl_sort_textures=false
gl_sprite_blend=false
gl_ssao=0
gl_ssao_portals=1
gl_ssao_strength=0.699999988079071
gl_texture_filter=4
gl_texture_filter_anisotropic=8
gl_texture_hqresize_maxinputsize=512
gl_texture_hqresize_mt_height=4
gl_texture_hqresize_mt_width=16
gl_texture_hqresize_multithread=true
gl_texture_hqresize_targets=7
gl_texture_hqresizemode=0
gl_texture_hqresizemult=1
gl_usecolorblending=true
gme_stereodepth=0
gus_memsize=0
gus_patchdir=
i_soundinbackground=false
inter_subtitles=false
invertmouse=true
invertmousex=false
joy_axespolling=true
k_allowfullscreentoggle=true
language=auto
longsavemessages=true
lookstrafe=false
m_blockcontrollers=false
m_filter=false
m_forward=1
m_noprescale=false
m_pitch=1
m_show_backbutton=0
m_showinputgrid=0
m_side=2
m_use_mouse=2
m_yaw=1
map_point_coordinates=true
midi_config=gzdoom
midi_dmxgus=false
midi_voices=32
mod_autochip=false
mod_autochip_scan_threshold=12
mod_autochip_size_force=100
mod_autochip_size_scan=500
mod_dumb_mastervolume=1
mod_interp=2
mod_samplerate=0
mod_volramp=2
mouse_capturemode=1
mouse_sensitivity=1
mus_enabled=true
nointerscrollabort=false
nomonsterinterpolation=false
opl_core=0
opl_fullpan=true
opl_numchips=2
opn_chips_count=8
opn_custom_bank=
opn_emulator_id=0
opn_fullpan=true
opn_run_at_pcm_rate=false
opn_use_custom_bank=false
osx_additional_parameters=
png_gamma=0
png_level=5
queryiwad=true
quicksavenum=-1
quicksaverotation=false
quicksaverotationcount=4
r_blendmethod=false
r_dynlights=true
r_fakecontrast=1
r_fullbrightignoresectorcolor=true
r_fuzzscale=true
r_line_distance_cull=0
r_linearsky=false
r_magfilter=false
r_minfilter=true
r_mipmap=true
r_mirror_recursions=4
r_models=true
r_multithreaded=1
r_noaccel=false
r_quakeintensity=1
r_sprite_distance_cull=0
r_spriteadjust=2
r_ticstability=true
save_dir=
save_formatted=false
saveloadconfirmation=true
savestatistics=0
screenshot_dir=
screenshot_quiet=false
screenshot_type=png
show_messages=true
showendoom=0
snd_aldevice=Default
snd_alresampler=Default
snd_backend=openal
snd_buffersize=0
snd_channels=128
snd_efx=true
snd_hrtf=-1
snd_mastervolume=0.3499998450279236
snd_mididevice=-5
snd_midiprecache=false
snd_musicvolume=0.5
snd_samplerate=0
snd_sfxvolume=1
snd_streambuffersize=64
snd_waterreverb=true
statfile=zdoomstat.txt
storesavepic=true
strictdecorate=false
telezoom=true
timidity_channel_pressure=false
timidity_chorus=0
timidity_config=gzdoom
timidity_drum_effect=false
timidity_drum_power=1
timidity_key_adjust=0
timidity_lpf_def=1
timidity_min_sustain_time=5000
timidity_modulation_envelope=true
timidity_modulation_wheel=true
timidity_overlap_voice_allow=true
timidity_pan_delay=false
timidity_portamento=true
timidity_reverb=0
timidity_reverb_level=0
timidity_surround_chorus=false
timidity_temper_control=true
timidity_tempo_adjust=1
turnspeedsprintfast=1280
turnspeedsprintslow=320
turnspeedwalkfast=640
turnspeedwalkslow=320
use_joystick=false
use_mouse=true
vid_activeinbackground=false
vid_aspect=0
vid_autoswitch=true
vid_brightness=0.09999990463256836
vid_contrast=1
vid_cropaspect=false
vid_defheight=1050
vid_defwidth=1680
vid_fullscreen=true
vid_gamma=1.549999475479126
vid_hdr=false
vid_hidpi=true
vid_maxfps=200
vid_preferbackend=0
vid_rendermode=4
vid_saturation=1
vid_scale_customheight=200
vid_scale_custompixelaspect=1
vid_scale_customwidth=320
vid_scale_linear=false
vid_scalefactor=1
vid_scalemode=0
vid_vsync=true
vk_debug=false
vk_debug_callstack=true
vk_device=0
vk_hdr=false
vr_hunits_per_meter=41
vr_ipd=0.06199999898672104
vr_screendist=0.800000011920929
wildmidi_config=
wildmidi_enhanced_resampling=true
wildmidi_reverb=false
win_h=1050
win_maximized=false
win_w=1680
win_x=0
win_y=0
xbrz_centerdirectionbias=4
xbrz_colorformat=0
xbrz_dominantdirectionthreshold=3.5999999046325684
xbrz_equalcolortolerance=30
xbrz_luminanceweight=1
xbrz_steepdirectionthreshold=2.200000047683716

[GlobalSettings.Unknown]

[Doom.Player]
autoaim=35
classicflight=false
color=40 cf 00
colorset=0
fov=90
gender=male
movebob=0.25
name=Player
neverswitchonpickup=false
playerclass=Normal (Rifle Start)
skin=base
stillbob=0
team=2
wbobfire=0
wbobspeed=1
wi_noautostartmap=false

[Doom.Player.Mod]
PB_tracerlight=0
b_flashlighthpos=0
b_flashlightlowq=0
b_flashlightmode=0
b_flashlightvpos=18
bd_ADSHoldDown=0
bd_RLOverloadCell=1
bd_RestoreCarbines=0
bd_SGAltAmmoSwap=0
bd_SGPumpFromHip=0
bd_UpgradeCarbine=0
bd_UpgradeGL=0
bd_UpgradeHMG=0
bd_UpgradePlasma=0
bd_UpgradeRevolver=0
bd_UpgradeShotgun=0
bd_bloodamount=2
bd_disablebloodyscreen=0
bd_enablesprint=0
bd_lowgraphicsmode=0
bd_morebloodmist=0
bd_sbartype=1
bd_shotgunskin=0
cl_MoveTilt=true
cl_step_delaymul=1
cl_step_volmul=7
disable_screentilt=0
disable_weaponsway=0
dpwh_chromaticAberration=true
dpwh_filmgrain=true
dpwh_filmictonemap=true
dpwh_naturalVignette=false
dsc_episode1_done=0
dsc_finish_wave=false
dsc_full_progress=0
dsc_heroic_mode=false
dsc_player_rank=-1
dsc_restore_defaults=false
dsc_scene_lut=TonemapDefault
dsc_screen_blur=false
dsc_spawn_factor=1.5
dsc_zfinish_wave=0
hx_altpower=false
hx_exkis=false
hx_nohelmet=false
hx_nokis=false
hx_nopowerups=false
hx_oldbars=false
mblur=false
mblur_autostop=true
mblur_blendmode=1
mblur_recovery=64
mblur_recovery2=90
mblur_samples=5
mblur_strength=64
mblur_threshold=30
pb_dasheffect=true
pb_doubletap=false
pb_maxtaptime=10
pb_olddualssgfiresystem=0
pb_toggle_aim_hold=false
py_weaponwheel_freeze=false
py_weaponwheel_invert=0
py_weaponwheel_musicfade=false
qtilt_strength=1
wt_autosave_interval=5
wt_blacklist_enable=true
wt_filter_iwad_monsters=5
wt_filter_iwad_weapons=5
wt_killsound=0
wt_lite_adv_visibility=2047
wt_lite_alpha=1
wt_lite_color_genociderank=0
wt_lite_color_labels=0
wt_lite_color_playerrank=0
wt_lite_color_totalkills=0
wt_lite_color_weaponkills=0
wt_lite_color_weaponname=0
wt_lite_color_weaponrank=0
wt_lite_offset_x=0
wt_lite_offset_y=0
wt_lite_orientation=0
wt_lite_scale=1
wt_lite_usefolders=0
wt_rankset_genocide=0
wt_rankset_player=0
wt_rankset_weapons=0
wt_scorecard_blackdisplays=false
wt_scorecard_scale=1
wt_scorecard_theme=0
wt_showlite=3
wt_ui_font=0
zm_doubletap=true
zm_fullbobspeed=8
zm_maxtaptime=10
zm_offsetdirection=false
zm_offsetmaxrange=30
zm_offsetspeed=75
zm_stillbob=false
zm_yawsway=true
zm_yawswaydirection=false
zm_yawswayfriction=10
zm_yawswayrange=2
zm_yawswayspeed=2

[Doom.ConsoleVariables]
addrocketexplosion=false
allcheats=false
am_backcolor=6c 54 40
am_cdwallcolor=4c 38 20
am_colorset=0
am_customcolors=true
am_drawmapback=1
am_efwallcolor=66 55 55
am_emptyspacemargin=0
am_fdwallcolor=88 70 58
am_followplayer=true
am_gridcolor=8b 5a 2b
am_interlevelcolor=ff 00 00
am_intralevelcolor=00 00 ff
am_lockedcolor=00 78 00
am_map_secrets=2
am_markcolor=2
am_markfont=AMMNUMx
am_notseencolor=6c 6c 6c
am_ovcdwallcolor=00 88 44
am_ovefwallcolor=00 88 44
am_overlay=0
am_ovfdwallcolor=00 88 44
am_ovinterlevelcolor=ff ff 00
am_ovlockedcolor=00 88 44
am_ovotherwallscolor=00 88 44
am_ovportalcolor=00 40 22
am_ovsecretsectorcolor=00 ff ff
am_ovsecretwallcolor=00 88 44
am_ovspecialwallcolor=ff ff ff
am_ovtelecolor=ff ff 00
am_ovthingcolor=e8 88 00
am_ovthingcolor_citem=e8 88 00
am_ovthingcolor_friend=e8 88 00
am_ovthingcolor_item=e8 88 00
am_ovthingcolor_monster=e8 88 00
am_ovthingcolor_ncmonster=e8 88 00
am_ovunexploredsecretcolor=00 ff ff
am_ovunseencolor=00 22 6e
am_ovwallcolor=00 ff 00
am_ovyourcolor=fc e8 d8
am_portalcolor=40 40 40
am_portaloverlay=true
am_rotate=0
am_secretsectorcolor=ff 00 ff
am_secretwallcolor=00 00 00
am_showgrid=false
am_showitems=true
am_showkeys=false
am_showkeys_always=false
am_showmaplabel=2
am_showmonsters=true
am_showsecrets=true
am_showthingsprites=0
am_showtime=true
am_showtotaltime=true
am_showtriggerlines=0
am_specialwallcolor=ff ff ff
am_textured=true
am_thingcolor=fc fc fc
am_thingcolor_citem=fc fc fc
am_thingcolor_friend=fc fc fc
am_thingcolor_item=fc fc fc
am_thingcolor_monster=fc fc fc
am_thingcolor_ncmonster=fc fc fc
am_thingrenderstyles=true
am_tswallcolor=88 88 88
am_unexploredsecretcolor=ff 00 ff
am_wallcolor=2c 18 08
am_xhaircolor=80 80 80
am_yourcolor=fc e8 d8
am_zoomdir=0
blood_fade_scalar=1
chat_substitution=false
chatmacro0=No
chatmacro1=I'm ready to kick butt!
chatmacro2=I'm OK.
chatmacro3=I'm not looking too good!
chatmacro4=Help!
chatmacro5=You suck!
chatmacro6=Next time, scumbag...
chatmacro7=Come here!
chatmacro8=I'll take care of it.
chatmacro9=Yes
cl_bbannounce=false
cl_bloodsplats=true
cl_bloodtype=0
cl_custominvulmapcolor1=00 00 1a
cl_custominvulmapcolor2=a6 a6 7a
cl_customizeinvulmap=false
cl_doautoaim=false
cl_gfxlocalization=3
cl_maxdecals=1024
cl_missiledecals=true
cl_pufftype=0
cl_rockettrails=1
cl_showmultikills=true
cl_showsecretmessage=true
cl_showsprees=true
cl_spreaddecals=true
classic_scaling_factor=1
classic_scaling_pixelaspect=1.2000000476837158
compatmode=2
con_alpha=0.75
con_centernotify=false
con_midtime=3
con_notablist=false
con_notifytime=3
con_scale=0
con_scaletext=0
crosshair=7
crosshaircolor=ff 00 00
crosshairforce=false
crosshairgrow=false
crosshairhealth=1
crosshairon=true
crosshairscale=0.39999985694885254
dehload=0
dimamount=-1
dimcolor=ff d7 00
displaynametags=0
dlg_musicvolume=1
dlg_vgafont=false
gl_aalines=false
gl_bandedswlight=false
gl_bloom=true
gl_bloom_amount=1.399999976158142
gl_brightfog=false
gl_enhanced_nightvision=true
gl_exposure_base=0.3499999940395355
gl_exposure_min=0.3499999940395355
gl_exposure_scale=1.2999999523162842
gl_exposure_speed=0.05000000074505806
gl_fogmode=1
gl_fuzztype=0
gl_interpolate_model_frames=true
gl_light_models=true
gl_lightadditivesurfaces=false
gl_lightmode=3
gl_menu_blur=-1
gl_paltonemap_powtable=2
gl_paltonemap_reverselookup=true
gl_precache=false
gl_scale_viewport=true
gl_sclipfactor=1.7999999523162842
gl_sclipthreshold=10
gl_spriteclip=1
gl_tonemap=0
gl_weaponlight=8
hud_althud=false
hud_althud_forceinternal=false
hud_althudscale=0
hud_ammo_order=0
hud_ammo_red=25
hud_ammo_yellow=50
hud_armor_green=100
hud_armor_red=25
hud_armor_yellow=50
hud_aspectscale=true
hud_berserk_health=true
hud_health_green=100
hud_health_red=25
hud_health_yellow=50
hud_scale=0
hud_showammo=2
hud_showangles=false
hud_showitems=true
hud_showlag=0
hud_showmonsters=true
hud_showscore=false
hud_showsecrets=true
hud_showstats=false
hud_showtime=0
hud_showweapons=true
hud_timecolor=5
hudcolor_ltim=8
hudcolor_statnames=6
hudcolor_stats=3
hudcolor_time=6
hudcolor_titl=10
hudcolor_ttim=5
hudcolor_xyco=3
inter_classic_scaling=true
log_vgafont=false
lookspring=true
m_quickexit=false
msg=0
msg0color=6
msg1color=5
msg2color=2
msg3color=3
msg4color=3
msgmidcolor=5
msgmidcolor2=4
nametagcolor=5
nocheats=false
os_isanyof=true
paletteflash=0
pickup_fade_scalar=1
r_deathcamera=false
r_drawfuzz=1
r_maxparticles=4000
r_portal_recursions=4
r_rail_smartspiral=false
r_rail_spiralsparsity=1
r_rail_trailsparsity=1
r_skymode=2
r_vanillatrans=0
sb_cooperative_enable=true
sb_cooperative_headingcolor=6
sb_cooperative_otherplayercolor=2
sb_cooperative_yourplayercolor=3
sb_deathmatch_enable=true
sb_deathmatch_headingcolor=6
sb_deathmatch_otherplayercolor=2
sb_deathmatch_yourplayercolor=3
sb_teamdeathmatch_enable=true
sb_teamdeathmatch_headingcolor=6
screenblocks=11
show_obituaries=true
snd_menuvolume=0.6000000238418579
snd_pitched=false
st_oldouch=false
st_scale=0
transsouls=0.75
ui_screenborder_classic_scaling=true
uiscale=0
underwater_fade_scalar=1
vid_cursor=None
vid_nopalsubstitutions=false
wi_percents=true
wi_showtotaltime=true
wipetype=2

[Doom.LocalServerInfo]
compatflags=-1172751401
compatflags2=523
forcewater=false
maxviewpitch=90
sv_corpsequeuesize=64
sv_disableautohealth=false
sv_dropstyle=0
sv_portal_recursions=4
sv_smartaim=0

[Doom.LocalServerInfo.Mod]
BrutalSpawnBalance=671
PinataParticles=true
V5_MODELS=false
bd_EnableEvilMarines=0
bd_GroundImps=0
bd_GroundRevenant=0
bd_HungryPinky=0
bd_NoASGWeapon=0
bd_NoAfrit=0
bd_NoAnnihilator=0
bd_NoArachnophyte=0
bd_NoArachnotron2=0
bd_NoArchvileHeal=0
bd_NoArchvileSummon=0
bd_NoAutoshotgunSergeant=0
bd_NoAutoshotgunUpgrade=0
bd_NoBFGBeamWeapon=0
bd_NoBaronBarrel=0
bd_NoBeamRevenant=0
bd_NoBelphegor=0
bd_NoBlackholeWeapon=0
bd_NoBloodDemon=0
bd_NoBrownImps=0
bd_NoCSSGWeapon=1
bd_NoCarbineWeapon=0
bd_NoCarbineZombie=0
bd_NoChaingunMajor=0
bd_NoClassicCommando=0
bd_NoCyberBaron=0
bd_NoCyberKnight=0
bd_NoCyberPaladin=0
bd_NoDBUpgrade=0
bd_NoDaedabus=0
bd_NoDarkImps=0
bd_NoDemolisher=0
bd_NoDemonTechSoldier=0
bd_NoDraugr=0
bd_NoFleshwizard=0
bd_NoFreezerWeapon=0
bd_NoHMGWeapon=0
bd_NoHeavyGLWeapon=0
bd_NoHellion=0
bd_NoHelmetAnimation=1
bd_NoHelmetSergeant=0
bd_NoHelmetZman=0
bd_NoIceVile=0
bd_NoInfernoArachnotron=0
bd_NoInfernus=0
bd_NoJuggernaut=0
bd_NoKnightCharge=0
bd_NoLMG=0
bd_NoM2PlasmaWeapon=0
bd_NoM2Upgrade=0
bd_NoMagCaco=0
bd_NoMancubusFlamer=0
bd_NoMechDemon=0
bd_NoMinigunUpgrade=0
bd_NoMinigunZombieman=0
bd_NoOverlord=0
bd_NoPhantasm=0
bd_NoPistolZman=0
bd_NoPlasmaZombie=0
bd_NoPulseCannonUpgrade=0
bd_NoPyroSergeant=0
bd_NoQuadSSG=0
bd_NoQuadSergeant=0
bd_NoRailgunWeapon=0
bd_NoRevolverWeapon=0
bd_NoRifleCommando=0
bd_NoRifleUpgrade=0
bd_NoRiotShieldGuy=0
bd_NoRocketSergeant=0
bd_NoSMGWeapon=0
bd_NoSavageImps=0
bd_NoSufferElemental=0
bd_NoSuperGLWeapon=0
bd_NoTriteElemental=0
bd_NoUnmakerUpgrade=0
bd_NoUpgrades=0
bd_NoVolcabus=0
bd_NoZSpecOps=0
bd_NoZmanAdvancedAttacks=0
bd_NoZmanGrenade=0
bd_NoZombieScientist=0
bd_ShutTheFuckUp=1
bd_TraditionalMode=0
bd_UnifiedExplosives=0
bd_VoidSpectre=0
bd_classicmonsters=0
bd_cooplives=0
bd_disablecrueltybonus=0
bd_disabledecorations=1
bd_disabledemonspheres=0
bd_disablefriendlymarines=0
bd_disablemapenhancements=0
bd_disablenewenemies=0
bd_disablenewguns=0
bd_disablescanner=0
bd_disablewaterripples2=1
bd_footstepsounds=1
bd_infinitecasings=0
bd_nobulletpenetration=1
bd_numcooplives=8
bd_replacemarines=0
bd_restrictedmode=0
bd_rocketbackblast=1
bd_shootablerocketammo=0
bd_voxeldec=1
be_AdditionalBonus=true
be_AmmoBonus=true
be_ExecutionsON=true
be_Fear=true
be_HealthBonus=true
be_OnlyBerserk=true
be_Protection=true
be_StaggerLenght=4
be_jumpanim=6
cl_fatalityspeed=1
cl_regen=0
cl_regenamount=35
donotclimb=0
donotdoublejump=0
donotsidestep=0
dsk_acceleration=1.5
fs_delay_mul=1
fs_volume_mul=1
gutaweather_clear_weight=1
gutaweather_enabled=true
gutaweather_fog_weight=1
gutaweather_rain_weight=1
gutaweather_snow_weight=1
hs_factor=2
hs_hitbox=true
isrunningzandronum=1
nashgore_bloodamount=255
nashgore_bloodspurt=false
nashgore_bloodtype=1
nashgore_corpseblood=false
nashgore_deathflip=true
nashgore_footprints=true
nashgore_gibamount=255
nashgore_gibtype=0
nashgore_icedeath=true
nashgore_maxcasings=50
nashgore_maxgore=1024
nashgore_splat=true
nashgore_spriteblood=false
nashgore_squish=true
nodoomguytalk=0
nopaineffect=0
noscreensplash=1
pb_EnableCarryableHealth=0
pb_HealthPackColor=0
pb_SmartScavenger=0
pb_SmartScavengerHealth=0
pb_SmartScavengerNoFade=0
pb_adashboost=10
pb_adashfriction=1
pb_airdash=false
pb_autojump=true
pb_crouchslide=true
pb_crouchspeed=0.5
pb_cslideduration=10
pb_cslidestrength=1.5
pb_cslidetype=0
pb_dash=true
pb_dashboost=1.3300000429153442
pb_dashheight=0.5
pb_doublejump=2
pb_doublejumpheight=1
pb_dropprevention=false
pb_ejumpmultiplier=1
pb_elevatorjump=false
pb_enemyexplosiondamage=true
pb_fadeonmapexit=false
pb_friction=1.600000023841858
pb_hazardmovement=false
pb_hook=0
pb_hookboost=1.5
pb_jumpheight=8
pb_knuckleanimationinstart=0
pb_landing=true
pb_landingsens=6
pb_landingspeed=0.25
pb_ledgegrab=true
pb_maxgroundspeed=15.100000381469727
pb_maxhopspeed=28
pb_minlanding=0.5
pb_movetype=0
pb_multipledashes=0
pb_qslideaccel=6
pb_qslideduration=8
pb_setgravity=1
pb_spawner_autoshotgun=0
pb_spawner_drum=0
pb_spawner_shotgunupgrade=0
pb_spawner_tiered=false
pb_strafemodifier=1.3300000429153442
pb_walkspeed=0.5
pb_wjdoublejumprenew=false
pb_wjump=false
pb_wjumpboost=1.5
pb_wjumpheight=0.75
pb_wslide=false
pb_wslidevelz=0.8999999761581421
performancemode=1
pk_acceleration=1
pk_bhopjumpheight=0.8500000238418579
q_1airaccel=1.5
q_3airaccel=0.75
q_strafetype=0
sv_ammorange=0
sv_bonusrange=0
sv_deathtilt=true
sv_forceregen=0
sv_glmax=0
sv_movetilt=false
sv_movetiltangle=0.014999999664723873
sv_movetiltscalar=0.20000000298023224
sv_movetiltspeed=15
sv_strafetilt=true
sv_strafetiltangle=0.5
sv_strafetiltinvert=false
sv_strafetiltspeed=1
sv_turntilt=true
sv_turntiltinvert=false
sv_turntiltscalar=1.5
sv_underwatertilt=true
sv_underwatertiltangle=0.20000000298023224
sv_underwatertiltscalar=1
sv_underwatertiltspeed=0.800000011920929
user_MaxDrawDistanceAMMOsparks=1024
user_MaxDrawDistanceHaze=4096
user_MaxDrawDistanceRain=384
user_MaxDrawDistanceStones=512
user_MaxDrawDistanceTorchFire=1024
zdoombrutalblood=2
zdoombrutaljanitor=0
zdoombrutaljanitorcasings=0
zm_adashboost=10
zm_adashfriction=1
zm_airdash=false
zm_autojump=true
zm_crouchslide=false
zm_crouchspeed=0.699999988079071
zm_cslideduration=13
zm_cslidestrength=1.5
zm_cslidetype=0
zm_dash=false
zm_dashboost=1.5
zm_dashheight=0.75
zm_doublejump=0
zm_doublejumpheight=1.2000000476837158
zm_dropprevention=false
zm_ejumpmultiplier=1
zm_elevatorjump=false
zm_friction=8
zm_hook=0
zm_hookboost=1.5
zm_jumpheight=5.5
zm_landing=false
zm_landingsens=6
zm_landingspeed=0.25
zm_ledgegrab=false
zm_maxgroundspeed=12
zm_maxhopspeed=28
zm_minlanding=0.5
zm_movetype=0
zm_multipledashes=0
zm_qslideaccel=6
zm_qslideduration=8
zm_rampjump=false
zm_rjumpmulti=1
zm_setgravity=0.5600000023841858
zm_speedometer=0
zm_strafemodifier=1
zm_walkspeed=0.699999988079071
zm_wjdoublejumprenew=false
zm_wjump=false
zm_wjumpboost=1.5
zm_wjumpheight=0.75
zm_wslide=false
zm_wslidevelz=0.8999999761581421
</details>

**Comment by cemtex-tk** [comment]
It is missing a texture definition.  I will fix now

**Comment by cemtex-tk** [comment]
I have uploaded the updated texture file

**Comment by Cacodemon345** [comment]
@vidaritos I recommend that you post INI config file as a file, not as a huge pile of text.

**Comment by vidaritos** [comment]
Thanks it works now

**Pull request merged**
