### PR TITLE
Minor Weapon touchups - Fixed MP40 Ejection, Desert Eagle Shell Ejection added, and MK2 error in master repo.

### PR DESCRIPTION
**Pull request by ADoomedSpaceMarine**
--Major shell ejection aesthetic fix for the MP40 secret SMG--
I ended up using the "give weapons command" and found that the MP40 had improper positioning of the shell ejection upon firing and aimed firing. This problem also incorporated improper casings. Although the MP40 is a very RARE item, for those who use the give weapons cheat they will be greeted by the shells ejecting from the correct side, but flying towards the incorrect side upon the execution of the fire and Fire2 states. I ended up utilizing the MP40CasingSpawnRight from the UAC SMG (second slot) and adjusted the actor's spawn offsets for proper positioning for ejection from the MP40. This led to it ejecting 9x19mm shells as it should in both the fire and fire2 states  and causing them to go the proper direction from the proper position on the SMG sprite. This fix applies to both the standard and vanilla states.

--Minor Update to Desert Eagle, adding shell ejection to "fire" state--
Also, as I ended up picking up the Desert Eagle one time I got lucky on episode four, I noticed the shell ejection was only working properly on the aimed fire. Without aiming, no shell was ejected. I ended up adding the same shell command in the aimed fire, with a vertical origin of -3 as to have it look more like it was coming out of the chamber versus from above the gun. 

Attached you will find the text versions of the changes. Within EXTRA.TXT the changes are on lines 141,161,179, and 197 on the DEAGLE.TXT the changes add a line at line 242. They're only minor fixes, but corrected some aesthetic issues that are fairly invasive to the experience.

--MK2 Plasma Error--
Upon running the newest commit the GZDoom Debugging console gave an error for an unrecognized time statement within line 794 of the MK2 Plasma Rifle's code, I am aware that there is some major revision coming to that weapon, and as of right now, unless a time is put for the tics of the M220 sprite in the line above it, the game will not successfully start. Modification is suggested upon soonest convenience to avoid beta player frustration. (I included a small snapshot of the problematic area in the MK2 decorate script)

[EXTRA.TXT](https://github.com/pa1nki113r/Project_Brutality/files/3168795/EXTRA.TXT) - MP40 Changes (Corrects issues with ejection directions and casing classifications on both the fire and fire2 states) (Illustrated below, due to time needed to capture and convert .avi to .gif, initial bug will not be illustrated. To replicate the issue use "give secretweapon_mp40" in the console while playing the unmodified PB 3.0 Master to see the initial issue prior to modification)

MP40 Shell fix 

[DEAGLE.TXT](https://github.com/pa1nki113r/Project_Brutality/files/3168779/DEAGLE.TXT) - Desert Eagle Changes (Adds shell ejection to fire state one.) (Illustrated below)

Desert Eagle Shell upon Fire State

Plasma Error on line 794, originating in line 793
Plasma Error

Also, in the case that this is entirely the wrong place for this, please forgive my misdirection, I am new to git, and my experience mainly resides in client side modifications, but was intrigued by potentially helping the team out from the weapons touch-up side through the git repo. The decorate files cannot be committed from my personal PC since I am not labeled as a contributor, but was wanting to shoot this out there if you guys perhaps found some use in it.

### CODE REVIEW

**Comment by Cacodemon345** [comment]
What's with the shotgun conflict?

**Comment by ADoomedSpaceMarine** [comment]
It may be because of the pull request being on the weapons touchup fork, versus the main fork. I'm not completely sure.

**Comment by ADoomedSpaceMarine** [comment]
All that is included is the text files. It may have been misplaced as previously state0, as I was just trying to get it in an area relevant to fixing some of the weapon issues.

**Comment by ADoomedSpaceMarine** [comment]
I ended up closing it due to the fact that I need to probably ask you guys where this thing belongs first, what it takes to become a contributor and such. I was trying to get it into a relevant area of change, but unfortunately, as stated, the conflicts originated from my lack of knowledge on Git itself, closing this to better find a place for it, and to request contribution rights. Forgive the misplacement.

**Comment by ADoomedSpaceMarine** [comment]
I will keep an eye on this thread as I wait to hear back from you guys. I was just trying to offer assistance and find out who these changes need to be run through to potentially help fix some of the smaller issues as a contributor. As demonstrated above, I have some hobbyist level knowledge of DECORATE, and as someone who really enjoys the work you guys have done wanted to help with some of the loose ends to potentially help you all get PB 3 released. I can't do much in the graphics department, but I can definitely weed out some of the aesthetic inconsistencies on my spare time for you all. I'm a full time engineering student with wife and kid, so messing around with Doom is a pass time when I have some down time. Just thought I would try to make myself useful to a project I believe in. 

Have a great night. Regards.

**Comment by ADoomedSpaceMarine** [comment]
Hey @pa1nki113r & @Cacodemon345, I have those changes ready in Git Desktop as a separate branch, but need contribution rights. It's all prepped and ready to go, but I just need the green light from the uptops of the project.  Sorry about the earlier nightmare. I ended up having to pretty much learn git tonight, so, with that behind me, I did want to inform you that I do have the changes in a branch called Deagle-shells,-MP40-fix, but cannot commit them until I end up getting the contribution ok from the project admins. I hope you guys have a great night. I look forward to our future correspondence after I wake up, and once again, forgive the confusion earlier.

**Comment by Cacodemon345** [comment]
It's perfectly OK for me.

**Pull request closed without merging**
