### PR TITLE
Some minor fixes

### PR DESCRIPTION
**Pull request by BasicallyTDuy**
I did notice that the first person legs sometimes get overlapped by the kicking animation if you spam kick with your fists selected
Doing the same thing will somehow also prevent you from moving
Also fixed the QuadSG's dual fire (1/1/24)
> Done

### CODE REVIEW

**Comment by JMartinez9820** [comment]
@DuyGamerLHB I actually fixed this already I believe. Instead of what you did, I used the PB_Handler class, with the function PlayerEntered.

**Comment by JMartinez9820** [comment]
https://github.com/pa1nki113r/Project_Brutality/pull/1203/commits/576e25e53c3b6781e1767bf66a10db7d2be56a67

You can see what I've done here

**Comment by DuyGamerLHB** [comment]
Oh

**Comment by generic-name-guy** [comment]
minor fixes
2.166 additions 37 commits

**Comment by generic-name-guy** [comment]
i'm gonna close this PR, make a branch with specifically these fixes and i'll merge it, but this is kind of a mess

**Comment by BasicallyTDuy** [comment]
Hold on lemme figure them out

**Pull request closed without merging**
