### PR TITLE
Force ZScript version 4.5.0

### PR DESCRIPTION
**Pull request by generic-name-guy**

### CODE REVIEW

**Comment by generic-name-guy** [comment]
Any updates on this being merged?

**Comment by popguy12** [comment]
what exactly does this change?
just some code errors and deprecation warnings?

**Comment by generic-name-guy** [comment]
> what exactly does this change? just some code errors and deprecation warnings?

It forces ZScript 4.5, which tells users on outdated versions to update.

**Comment by popguy12** [comment]
looks clean to me, ill see about gettin it merged

**Comment by generic-name-guy** [comment]
> looks clean to me, ill see about gettin it merged

cool

**Pull request merged**
