### PR TITLE
New Helmet Anim With Sounds

### PR DESCRIPTION
**Pull request by popguy12**

### CODE REVIEW

**Comment by popguy12** [comment]
possibly hold off on this actually, might wanna have it reanimated and cleaned up

**Comment by JMartinez9820** [comment]
@popguy12 
I actually found the original animation that Warry posted in a zip before Kamil's optimization came. I have the original animation but optimized with PNGGauntlet so it doesn't look as crusty/deep fried as the one currently in this PR

**Comment by popguy12** [comment]
yea i went to try and find that, but i didnt have it in my files, i think i wanna ask warry about redoin the hands on the last few frames tho, or maybe just clean em up myself

**Comment by JMartinez9820** [comment]
If you want this PR to be held off for now you can either close it and reopen it later, or make it as a draft (where it says Still in progress?). If you want the cleaner original animation here it is:
[PB_HelmetOptimizedBetter.zip](https://github.com/pa1nki113r/Project_Brutality/files/7724448/PB_HelmetOptimizedBetter.zip)

**Comment by popguy12** [comment]
alright, i think this is ready, hopefully that single conflict didnt break anything

**Pull request merged**
