### PR TITLE
Unused sprite and code removal

### PR DESCRIPTION
**Pull request by DemonSlayer1997**
I removed unnecessary sprites and what is no longer used in PB

### CODE REVIEW

**Comment by Epictyphlosion** [comment]
There's still a lot of unused sprites for the pistol

**Comment by D3X1KAXYZ** [comment]
Since this is going into the master, revert my changes.

**Review by D3X1KAXYZ — CHANGES_REQUESTED** [review]
need reverted

**Comment by Epictyphlosion** [comment]
Umm, why'd you close it?

**Comment by JMartinez9820** [comment]
Possible merge conflicts. I was the one that instructed him to close it after me and him had a brief talk in DMs.

**Pull request closed without merging**
