### PR TITLE
Basically rescripting almost the entire mod

### PR DESCRIPTION
**Pull request by DuyGamerLHB**
It's going to be my second yet last pull request since I don't wanna interfere any further
- Fixed Belphegor's ball not doing a single drop of damage
- Patched corpses' states (regrowing limbs from getting kicked, or by lying near an explosion's radius)
- Fixed endlessly shootable pinky variants
- Fixed some double drops
- Fixed the player's legs disappearing from existence after climbing a ledge
- Added demon energy fading effect
- The player's execution states will now take away the **CantWeaponSpecial** token
- Fixed an issue where the player can't kick after resurrection
- Fixed the weird pump shotgun shell altering & picking up live shells can now refill your ammo
- Certain weapons no longer pull out a non-existent mag on changing ammo type or reloading after unloading
- Fixed the issue where the Auto Shotgun didn't take away ammo properly, which resulted in an infinite ammo glitch
- Fixed the dual weapons reloading unintentionally after climbing a ledge or an execution
- 1st Person explosion death now translates your legs' color & cleared out kick overlay on death
- Burning armless zombies & added missing sprites for the zombiemen variations' specific states
Also some of the fixes aren't mine officially as they're merged to mine from the main staging branch

### CODE REVIEW

**Comment by generic-name-guy** [comment]
what the fuck 458 FILES CHANGED!?!?!!!!??

**Comment by inkoalawetrust** [comment]
God fucking damn that's like a whole branch of its' own. There's definitely a lot more changed here than one projectile and a "some" fixes. A breakdown would be nice, considering it's even stuttering to show the diff on the GitHub site.

**Comment by Brugarolas** [comment]
Well, like 90% of the file changes are due to the removal of the "savage imp" an all his sprites. But still too damn large, though

**Comment by Brugarolas** [comment]
If my opinion is useful for anything, I've been playing with this branch for 2 days and so far so good, except for a small graphical glitch when you swap your weapon to any shotgun, something which may be happening because of my HD sprites mod, but that does not happen on main branch.

**Comment by DuyGamerLHB** [comment]
> If my opinion is useful for anything, I've been playing with this branch for 2 days and so far so good, except for a small graphical glitch when you swap your weapon to any shotgun, something which may be happening because of my HD sprites mod, but that does not happen on main branch.

Weird, I don't see anything strange, what exactly happened tho?

**Comment by Brugarolas** [comment]
Every time I connect to GitHub there are new changes in this branch. And every time I update the .pk3 to test this branch I discover that changes break save game compatibility. Ok, spent last 4 hours playing and testing this branch. So far, so good.

But please, unless they are related changes, consider creating a new branch and a new pull request for more changes. Or talk with who you have to talk to merge this as soon as possible, because seeing this PR exponentially growing makes me anxious. This could be (barely but) considered a fork of Project Brutality.

P.S.: Why was Savage Imp deleted,  by the way? I think it was cool

**Comment by JMartinez9820** [comment]
> P.S.: Why was Savage Imp deleted, by the way? I think it was cool

@Brugarolas The Savage Imp is going to be replaced with a different and new design, other monsters are going to receive the same treatment of new designs

**Comment by brosett311** [comment]
> Every time I connect to GitHub there are new changes in this branch. And every time I update the .pk3 to test this branch I discover that changes break save game compatibility. Ok, spent last 4 hours playing and testing this branch. So far, so good.
> 
> But please, unless they are related changes, consider creating a new branch and a new pull request for more changes. Or talk with who you have to talk to merge this as soon as possible, because seeing this PR exponentially growing makes me anxious. This could be (barely but) considered a fork of Project Brutality.
> 
> P.S.: Why was Savage Imp deleted, by the way? I think it was cool

This is a user generated branch consisting of unofficial fixes. As this isn't a mainline branch, we will need to sift through piece by piece and determine whether these "fixes" should be merged. I suggest sticking to the staging branch moving forward.

**Comment by popguy12** [comment]
is this still okay to merge?

**Comment by DuyGamerLHB** [comment]
> is this still okay to merge?

There's nothing left I can do so Idunno

**Comment by DuyGamerLHB** [comment]
There we go

**Comment by popguy12** [comment]
alright, if all looks well i think we can get it merged i think
is the list of changes in the first post still mostly accurate?

**Comment by generic-name-guy** [comment]
there's a lot of good fixes but also a lot of old changes that got reverted but still count in the files added and removed, i'd say test it thoroughly to see if there are any issues first

**Comment by DuyGamerLHB** [comment]
Okay I might have accidentally put kickable and teleportable grenades into this branch weeks ago

**Comment by DuyGamerLHB** [comment]
ah

**Pull request merged**
