### PR TITLE
Various changed/bugfixes

### PR DESCRIPTION
**Pull request by tunbridgep**
so that keys won't need to be rebound when going from one to the other

### CODE REVIEW

**Comment by JMartinez9820** [comment]
If this applies to Brutal Doom v21 mode, Brutal Doom v21 mode is going to get removed in final release of Project Brutality 3.0. This was a team decision, and the fact that Project Brutality 3.0 is now going to be its separate mod and independent from Brutal Doom.

**Comment by tunbridgep** [comment]
No, this is not about the built-in brutal doom implementation. This is just
a quick fix so that when you decide to play the latest official brutal doom
release instead of project brutality, you don't have to rebind a bunch of
identical keys (like grenade tossing).

I know that compatibility with regular brutal doom is not really the goal
of this mod, but this is such a trivial change that makes life so much
easier for people who play both mods at different times, that I thought it
was worth submitting.

**Comment by JMartinez9820** [comment]
Not to be rude, but why make this a pull request? This can be an add-on rather than in the mod itself

**Comment by tunbridgep** [comment]
It seems more like a design oversight and something that should be fixed or
changes to me rather than some external thing to be bolted on

**Comment by MekBoss** [comment]
BD use crutches and hacks to use weapon functions, i.e. it use uoutdated, in present days, ineffective and too costly, from the point of processor time, way to reload/aim/etc weapon. I dont know why mark holding so much into "zadornium" support, since gzdoom slowly gain more and more stable support for coop gameplay mode.

PB zscript build already got rid of it and use more advanced stuf for all of this. So fix something which soon would be thrown away on the dump of a history is pointless.

**Comment by tunbridgep** [comment]
I think this thread is going way off topic. Normally I'd agree that
supporting brutal doom is pointless. But in this case it costs nothing to
do so. It's simply renaming an alias, which is a few harmless keyconf
changes that barely affect the mod and while it may not directly affect
running brutal doom or making this mod not compatible with it in the
traditional sense (ie it's got nothing to do with running this along side
brutal doom or actively changing anything to do with how either mods
fundamentally work), it seems worth it to me since it'll make life so much
easier for players of both mods and costs virtually nothing.

The second changeset has nothing at all to do with brutal doom. I made a
mistake by not using separate branches, so both things got added to the
same pull request. The second change set increases compatibility for
virtually no cost

**Comment by tunbridgep** [comment]
That's a good idea actually. It probably makes sense to leave the aliases
unchanged from the PB originals, but then adding in the brutal ones to
point at these ones. Your suggestion works just as well too.

Either way, I wholeheartedly agree it's better to double up the aliases

**Comment by tunbridgep** [comment]
I have added the old aliases as alternates based on @Cacodemon345's suggestions. Sorry it took so long, I was very busy the last week or so.

**Comment by tunbridgep** [comment]
Also my apologies, as I am still new to this whole collaboration and branching thing, my OTEX additions to the TERRAIN lump are included in this pull request. They are good features to have, but if needed I can put them into a different branch.

**Comment by Cacodemon345** [comment]
I will wait until PA1N also approves this. You do, too.

**Pull request merged**
