### PR TITLE
MG42 minor fixes, restored uncompressed M1 Plasma and M2 Plasma sprites

### LINKED ISSUE #155: Dual wielding
Doesn't double ammo amount.

### LINKED ISSUE #179: Suggestion: Fix all startup warnings
There were lots of warnings already, but with the recently introduced check for missing drop items, the startup log becomes a wall of text. It's very easy to miss something important there.
```
Invalid data encountered for texture Project_Brutality-master.zip:sprites/weapons/ssg/thumbs.db
Invalid data encountered for texture Project_Brutality-master.zip:textures/thumbs.db

Attempting to remap texture SKYEAR5 to non-existent lump SKYEAR5HD

Attempt to get invalid state FinishInspect from actor Shot_Gun.
Script warning, "Project_Brutality-master.zip:actors/items/ammo/genericammo.dec" line 77:
Icon 'NULL' for 'TankAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/items/ammo/genericammo.dec" line 96:
Icon 'NULL' for 'MechAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/items/ammo/genericammo.dec" line 116:
Icon 'NULL' for 'HeavyMachinegunAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/items/ammo/genericammo.dec" line 135:
Icon 'NULL' for 'MechRocketAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/items/ammo/genericammo.dec" line 153:
Icon 'NULL' for 'MechLaserAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/items/ammo/genericammo.dec" line 172:
Icon 'NULL' for 'MechMOrtarAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/items/ammo/genericammo.dec" line 191:
Icon 'NULL' for 'HelicopterRocketAmmo' not found
Bad hex number: no
Script error, "Project_Brutality-master.zip:actors/gore/gore2.dec"line 713:
NODELAY may only be used immediately after Spawn:
Script error, "Project_Brutality-master.zip:actors/gore/gore2.dec"line 795:
NODELAY may only be used immediately after Spawn:
Script warning, "Project_Brutality-master.zip:actors/player/player.dec" line 32:
Tried to define class 'IsTacticalClass' more than once. Renaming class to 'IsTacticalClass@Project_Brutality-master.zip@actors/player/player.dec'
Bad hex number: no
Attempt to get invalid state NoAmmo from actor BDPistol.
Attempt to get invalid state NoAmmo from actor BDPistol.
Script warning, "Project_Brutality-master.zip:actors/weapons/slot2/dualpistol.dec" line 5:
Tried to define class 'PB_PistolFireAnimation1' more than once. Renaming class to 'PB_PistolFireAnimation1@Project_Brutality-master.zip@actors/weapons/slot2/dualpistol.dec'
Script warning, "Project_Brutality-master.zip:actors/weapons/slot2/uacsmg.dec" line 753:
Icon 'ATFLA0' for 'SMGAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/weapons/slot4/hmgweapon.dec" line 38:
Icon 'HMGNA0' for 'HMGAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/weapons/slot9/demontech.dec" line 1120:
Icon 'MDHPH1' for 'Demonpower' not found
Script warning, "Project_Brutality-master.zip:actors/weapons/slot3/quadbarrel.dec" line 12:
Icon 'QSGSA1' for 'QSSGAmmoCounter' not found
Script warning, "Project_Brutality-master.zip:actors/weapons/extra.dec" line 1588:
Icon 'HBUSD1' for 'BuzzSawAmmo' not found
Script warning, "Project_Brutality-master.zip:actors/weapons/slot1/saw.dec" line 69:
Unknown class name 'UMGSelected' of type 'Inventory'
Script warning, "Project_Brutality-master.zip:actors/weapons/slot3/shotgun.dec" line 957:
Numeric type expected, got "Auto"
Undefined drop item class ShieldSphere referenced from actor PoorMeanDemonLostHisArm
Undefined drop item class ShieldSphere referenced from actor TriteElemental
Undefined drop item class ShieldSphere referenced from actor HellsFury
Undefined drop item class ShieldSphere referenced from actor Cybruiser
Undefined drop item class ShieldSphere referenced from actor Cyberbaron
Undefined drop item class ShieldSphere referenced from actor SuperOverlord
Undefined drop item class ShieldSphere referenced from actor OverLord
Undefined drop item class ShieldSphere referenced from actor Volcabus
Undefined drop item class ShieldSphere referenced from actor Daedabus
Undefined drop item class ShieldSphere referenced from actor Annihilator
Undefined drop item class ShieldSphere referenced from actor Vore
Undefined drop item class ShieldSphere referenced from actor Arachnotron2
Undefined drop item class ShieldSphere referenced from actor ArachnotronX
Undefined drop item class ShieldSphere referenced from actor FleshWizard
Undefined drop item class ShieldSphere referenced from actor HellWarrior
Undefined drop item class ShieldSphere referenced from actor CyberPaladin
Undefined drop item class ShieldSphere referenced from actor CyberKnight
Undefined drop item class ShieldSphere referenced from actor FriendlyCyberKnight
Undefined drop item class ShieldSphere referenced from actor PhasicKnightX
Undefined drop item class ShieldSphere referenced from actor BloodDemonClone
Undefined drop item class ShieldSphere referenced from actor Bloodfiend
Undefined drop item class ShieldSphere referenced from actor DemonX
Undefined drop item class ShieldSphere referenced from actor MagCaco
Undefined drop item class NewChain_Gun referenced from actor ChaingunGuy2
Undefined drop item class Imp2DropSpawner referenced from actor DNImpVariant1
Undefined drop item class GrenadeAmmo referenced from actor ChainsawZombie
Undefined drop item class GrenadeAmmo referenced from actor ChainsawLabguy
Undefined drop item class GrenadeAmmo referenced from actor ZombieScientist
Undefined drop item class GrenadeAmmo referenced from actor FemaleScientist
Undefined drop item class GrenadeAmmo referenced from actor Labguy
Undefined drop item class HandgunAmmo referenced from actor BrutalDoomerPistolStart
Undefined drop item class PistolAmmo referenced from actor BrutalDoomerPistolStart
Undefined drop item class SlotOWN0 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN9 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN8 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN7 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN6 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN5 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN4 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN3 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN2 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN1 referenced from actor BrutalDoomer
Undefined drop item class SlotOWN0 referenced from actor Doomer
Undefined drop item class SlotOWN9 referenced from actor Doomer
Undefined drop item class SlotOWN8 referenced from actor Doomer
Undefined drop item class SlotOWN7 referenced from actor Doomer
Undefined drop item class SlotOWN6 referenced from actor Doomer
Undefined drop item class SlotOWN5 referenced from actor Doomer
Undefined drop item class SlotOWN4 referenced from actor Doomer
Undefined drop item class SlotOWN3 referenced from actor Doomer
Undefined drop item class SlotOWN2 referenced from actor Doomer
Undefined drop item class SlotOWN1 referenced from actor Doomer
Undefined drop item class Shells referenced from actor BDECBarrel
Undefined drop item class CLIP1Drop referenced from actor BDECBarrel
Undefined drop item class Clips referenced from actor BDECBarrel
Undefined drop item class CLIP1Drop referenced from actor NSHangingBody
Undefined drop item class CLIP1Drop referenced from actor HangingBody
Undefined drop item class Shells referenced from actor ImpaledMarineAlive1d
Undefined drop item class Clips referenced from actor ImpaledMarineAlive1d
Undefined drop item class Shells referenced from actor ImpaledMarineAlive1c
Undefined drop item class Clips referenced from actor ImpaledMarineAlive1c
Undefined drop item class Shells referenced from actor ImpaledMarineAlive1b
Undefined drop item class Clips referenced from actor ImpaledMarineAlive1b
Undefined drop item class Shells referenced from actor ImpaledMarineAlive1a
Undefined drop item class Clips referenced from actor ImpaledMarineAlive1a
Undefined drop item class Shells referenced from actor ImpaledMarineAlive2d
Undefined drop item class Clips referenced from actor ImpaledMarineAlive2d
Undefined drop item class Shells referenced from actor ImpaledMarineAlive2c
Undefined drop item class Clips referenced from actor ImpaledMarineAlive2c
Undefined drop item class Shells referenced from actor ImpaledMarineAlive2b
Undefined drop item class Clips referenced from actor ImpaledMarineAlive2b
Undefined drop item class Shells referenced from actor ImpaledMarineAlive2a
Undefined drop item class Clips referenced from actor ImpaledMarineAlive2a
Undefined drop item class Shells referenced from actor ImpaledMarineAlive2
Undefined drop item class Clips referenced from actor ImpaledMarineAlive2
Undefined drop item class Shells referenced from actor ImpaledMarineAlive1
Undefined drop item class Clips referenced from actor ImpaledMarineAlive1
Undefined drop item class Shells referenced from actor DeadLiveStick
Undefined drop item class Clips referenced from actor DeadLiveStick
Undefined drop item class Shells referenced from actor DeadDeadStick
Undefined drop item class Clips referenced from actor DeadDeadStick

DistX in slider decal Drops is unsupported

Editor number 15857 defined twice for classes 'LargeRainSpawner' and 'BDECcagedlight'

Unknown flat OWATER01
Unknown flat OWATER02
Unknown flat OWATER03
Unknown flat OWATER04
Unknown flat OWATER05
Unknown flat OWATER06
Unknown flat OWATER07
Unknown flat OWATER08
Unknown flat OSLUDG01
Unknown flat OSLUDG02
Unknown flat OSLUDG03
Unknown flat OSLUDG04
Unknown flat OSLUDG05
Unknown flat OSLUDG06
Unknown flat OSLUDG07
Unknown flat OSLUDG08
Unknown flat ONUKEA01
Unknown flat ONUKEA02
Unknown flat ONUKEA03
Unknown flat ONUKEA04
Unknown flat ONUKEA05
Unknown flat ONUKEA06
Unknown flat ONUKEA07
Unknown flat ONUKEA08
Unknown flat OLAVAC01
Unknown flat OLAVAC02
Unknown flat OLAVAC03
Unknown flat OLAVAC04
Unknown flat OLAVAC05
Unknown flat OLAVAC06
Unknown flat OLAVAC07
Unknown flat OLAVAC08
Unknown flat OLAVAD01
Unknown flat OLAVAD02
Unknown flat OLAVAD03
Unknown flat OLAVAD04
Unknown flat OLAVAD05
Unknown flat OLAVAD06
Unknown flat OLAVAD07
Unknown flat OLAVAD08
Unknown flat OGOOPY01
Unknown flat OGOOPY02
Unknown flat OGOOPY03
Unknown flat OGOOPY04
Unknown flat OGOOPY05
Unknown flat OGOOPY06
Unknown flat OGOOPY07
Unknown flat OGOOPY08
Unknown flat OICYWA01
Unknown flat OICYWA02
Unknown flat OICYWA03
Unknown flat OICYWA04
Unknown flat OICYWA05
Unknown flat OICYWA06
Unknown flat OICYWA07
Unknown flat OICYWA08
Unknown flat OBLODA01
Unknown flat OBLODA02
Unknown flat OBLODA03
Unknown flat OBLODA04
Unknown flat OBLODA05
Unknown flat OBLODA06
Unknown flat OBLODA07
Unknown flat OBLODA08
Unknown flat OTAR__01
Unknown flat OTAR__02
Unknown flat OTAR__03
Unknown flat OTAR__04
Unknown flat OTAR__05
Unknown flat OTAR__06
Unknown flat OTAR__07
Unknown flat OTAR__08
```

### LINKED ISSUE #341: crash issue when loading saves and starting a game
so ive figured it out, all those odd bugs with everything going super fast is caused by this:

if you move your mouse/aim during loading a save or beginning a new game, the game will go super fast and crash. not too sure why this is but this is the main cause

tested on gzdoom 4.3.3, and project brutality without any other addons

### LINKED ISSUE #730: Demon tech trooper doesn't scream when leg is blown off
I blew off the leg of the Demon tech trooper and he did the screaming animation, but unlike the other zombie men he was completely silent.

### LINKED ISSUE #731: MG42 ADS crosshair still visible
Crosshair still visible while ADS with MG42

### LINKED ISSUE #734: Project-Brutality-Master: no reload button
I downloaded the new version of P.B. and I thought it was really amazing, again the team behind the game's production did a great job, but there was a detail that I would say is fatal for gameplay in general, which was the lack of a button to reload weapons. I looked in all the control and command options and I didn't find it. I don't know if it's a bug, but at least for me it doesn't have a command to reload weapons. That's pretty uncomfortable in a way and I hope the producers will take a look or do something about it, that's it. Thanks for listening.

### PR DESCRIPTION
**Pull request by JMartinez9820**
- Brightmaps for MG42 done (thanks Cocoademon for the barrel change brightmaps)
- MG42 no longer alerts enemies when pressing alt fire
- Removed old ass MG42
- Fixed corrupted Minigun spin sound for the Gatling mode
- MG42 Overheat changes, see new comment

Fixes #730
Fixes #731
Fixes #155 
Fixes #341 
Fixes #179
Fixes #734

### CODE REVIEW

**Comment by JMartinez9820** [comment]
This pull request can be safe to merge now.

**Comment by JMartinez9820** [comment]
MG42 Overheating update:
MG42 now requires at least 120 rounds to overheat.
A small pause will be active when the barrel overheats, along with an overheat sound (overheat sound from freesound.com, credits: Marregheriti) being played.
When the barrel is overheated, the player has to press Reload or Fire to change barrels. If the Heat meter reaches half way when cooling, the player can fire weapon again.
MG42 casing spawns changed, scale and bounce count lowered.
Fixed certain sprite issues

**Comment by JMartinez9820** [comment]
Converted my pull request to a draft for the time being due to an issue with spent casings spawning incorrectly.

**Comment by Ferlocutor456** [comment]
disculpen al parecer cuando descargo el zip no descargar completamente el proyect brutality y no me arranca, me pueden ayudar?

**Comment by JMartinez9820** [comment]
> disculpen al parecer cuando descargo el zip no descargar completamente el proyect brutality y no me arranca, me pueden ayudar?

Perdón por la mala traducción, hablo inglés y estoy usando el traductor de Google:

@Ferlocutor456 Intente descargar el enlace de Mediafire que hice aquí: https://www.mediafire.com/file/7ul3hjy3ufmeeup/Project_Brutality-JMartinezBranch.zip/file

**Comment by Ferlocutor456** [comment]
> > disculpen al parecer cuando descargo el zip no descargar completamente el proyect brutality y no me arranca, me pueden ayudar?
> 
> Perdón por la mala traducción, hablo inglés y estoy usando el traductor de Google:
> 
> @ Ferlocutor456 Intente descargar el enlace de Mediafire que hice aquí: https://www.mediafire.com/file/7ul3hjy3ufmeeup/Project_Brutality-JMartinezBranch.zip/file

thanks bro no problem, if i had another problem i will tell you

**Comment by JMartinez9820** [comment]
Pull request closed until further notice.

**Comment by pa1nki113r** [comment]
Lets fix that one small file and we can merge it

**Comment by JMartinez9820** [comment]
@pa1nki113r This branch should be safe to merge now. Changes to CVARS maybe be put on another PR.

**Pull request merged**
