### PR TITLE
Fix non jit vm crashes

### PR DESCRIPTION
**Pull request by emileb**
Added NULL checks to fix crashes when running on the non JIT VM (As used in Delta Touch)

### CODE REVIEW

**Comment by JMartinez9820** [comment]
@emileb You may want to sync your branch with the latest changes from master, as your branch is 2 commits behind master. PBMonster.zc and ZombieMan.zc will also change so update your changes to match with those too. Do you use Discord? If so, if you need help, DM me if necessary.

**Comment by emileb** [comment]
@JMartinez9820 Thanks for the head up, now updated. If anyone has a chance might be good to see if these small changes could go in master - I don't believe they will break anything (but should be tested first ofc). Yep on Discord under emile_b, i'm in the PB server, and thanks for the offer of help ;)

**Comment by JMartinez9820** [comment]
Hello again, Project Brutality's master branch recently got updated 12 hours ago, you may want to sync your branch with the latest changes from master. I recommend syncing your branches/forks every time the master branch gets updated, to prevent the one step forward, two steps back issue.

**Comment by emileb** [comment]
> Hello again, Project Brutality's master branch recently got updated 12 hours ago, you may want to sync your branch with the latest changes from master. I recommend syncing your branches/forks every time the master branch gets updated, to prevent the one step forward, two steps back issue.

Thanks, updated.

**Comment by goldenmob72** [comment]
We really appreciate you helping w/ PB, You are awesome for that   😉

**Pull request merged**
