### PR TITLE
Restoring all recent changes prior to optimization

### PR DESCRIPTION
**Pull request by JMartinez9820**
This pull request aims to restore all new changes made prior to Kamil's pull request removing the tanks and optimizing some sprites. Unfortunately his pull request resulted into many steps going backwards. So this PR aims to restore all recent changes.

### CODE REVIEW

**Comment by pa1nki113r** [comment]
PM me once its ready

**Comment by JMartinez9820** [comment]
@pa1nki113r This PR should be safe to merge now, I think I may have gotten everything, popguy already took care of restoring the freeze ray.

**Comment by popguy12** [comment]
oh is that why the laser stuff disappeared? not just a github bug?

**Comment by JMartinez9820** [comment]
> oh is that why the laser stuff disappeared? not just a github bug?

@popguy12 Yes. Some of the recent changes got removed due to Kamil's branch not being up to date. Resulting in the one step forward, two steps back issue.

**Pull request merged**
