### PR TITLE
HUD tweaks

### PR DESCRIPTION
**Pull request by neonvortex**
- Added explosive ammo to the HUD when using HDMR's grenade launcher mode
- Added a cooldown bar and shotgun ammo to the HUD when using the Chainsaw and you have an SSG

### CODE REVIEW

**Comment by popguy12** [comment]
it seems the chainsaw stuff doesnt seem to be workin
good work with the HDMR stuff tho, even made sure it doesnt show when akimbo

**Comment by neonvortex** [comment]
what's the issue with the chainsaw?
can you send me a screenshot

**Comment by neonvortex** [comment]
oh wait nevermind i forgot
the chainsaw needs some extra code

**Comment by neonvortex** [comment]
Fixed

**Comment by popguy12** [comment]
coolio, think this is safe to merge now

**Pull request merged**
