### PR TITLE
Pull back changes from master

### PR DESCRIPTION
**Pull request by Cacodemon345**

### CODE REVIEW

**Comment by Ventolin1369** [comment]
This is one of the problems I ran into when I launched PB 3.0 with the wad
Monolaik.

**Comment by Ventolin1369** [comment]
Why doesn't your latest build of Project Brutality 3.0 work on Delta Touch
anymore? That really sucks, because it's all I was playing on my phone for
awhile now. . .

**Comment by JMartinez9820** [comment]
@Ventolin1369 Delta Touch support has been officially scrapped as Project Brutality now requires 4.1.3. Although I have got the word the PB 3.0 works with Delta Touch now, just update your Delta Touch version. If you need more help I can help or others on the PB server. Just have a profile picture on your Discord account to follow its verification process.
https://discord.gg/2hJxXPc

**Comment by JMartinez9820** [comment]
@Ventolin1369 I have got the word the PB 3.0 works with Delta Touch now, just update your Delta Touch version. If you need more help I can help or others on the PB server. Just have a profile picture on your Discord account to follow its verification process.
https://discord.gg/2hJxXPc

**Comment by JMartinez9820** [comment]
Follow this screenshot if needed.
https://cdn.discordapp.com/attachments/327164791628234754/612691930350092289/Screenshot_20190818-125832.jpg

**Comment by Ventolin1369** [comment]
This is what it did when I followed your instructions in that screenshot. .
.

**Comment by JMartinez9820** [comment]
I don't see a screenshot on your post. Drag and drop the screenshot into the text box when typing on it

**Comment by Ventolin1369** [comment]
You get it that time?

**Comment by Ventolin1369** [comment]
Hello?

**Comment by JMartinez9820** [comment]
@Ventolin1369 I would suggest joining the Project Brutality Discord now if you want too, the link is above some comments. If needed again here it is: https://discord.gg/2hJxXPc

**Pull request merged**
