### PR TITLE
Add POSSITEM source and credits, fix Demon Rifle altfire CTD bug

### PR DESCRIPTION
**Pull request by Cacodemon345**
Also fixes a couple of other bugs.

### CODE REVIEW

**Comment by JMartinez9820** [comment]
Bug report: Although the Demon Tech Rifle crash bug on overhauled enemies is fixed, however, where they're in possession state, shooting the Demon Tech Rifle will crash the game. I have got no crash log from it. Other weapons don't cause this.

**Comment by JMartinez9820** [comment]
Update: It seems that other weapons are crashing as well when an overhauled enemy is at possession state.

**Comment by Cacodemon345** [comment]
I frankly got no idea how to fix it properly.

**Comment by Cacodemon345** [comment]
I fixed it finally.

**Comment by JMartinez9820** [comment]
Hey Cacodemon, have you checked my pull request to this PR yet? I have fixed several bugs in there and applied your Demon Tech Rifle crash bug fix to the Labguys.

**Pull request merged**
