### PR TITLE
Archvile arm fixed, Afrit gore updates, Nazi updates and sprite changes

### LINKED ISSUE #819: .zip compile is damaged

### PR DESCRIPTION
**Pull request by JMartinez9820**
Archvile arm spawn fixed
Afrit gore changes; now has an arm spawned, fixed torso exploding gore and horns spawn when the head is blown up (all sprites by Keeper). Afrit fall death also has blood color fixed (sprites by Keeper.)

Fixes #819 (Reason: Invalid/won't fix.)

### CODE REVIEW

**Comment by Ganbare-Lucifer** [comment]
The Afrit Head Chunks are on the Hell Knight's MoreDeaths folder instead of the proper Afrit folder...

**Comment by JMartinez9820** [comment]
@Ganbare-Lucifer Fixed. Thanks for catching that. I was working with someone to make this possible, and didn't catch that they were in the Hell Knight's folder. Since the Afrit Head chunks are basically recolored Hell Knight head chunks.

**Comment by JMartinez9820** [comment]
Small updates:
Afrit head chunks removed from hell knight folder. Minor slip up sorry.
Afrit and Infernus plasma deaths added
Fixed Nazi deaths again
Fixed Auto Shotty Guy shell spawn from dying.
Another dumbass slip up I made. Forgot to remove the old Nazi rotation sprites so this is now fixed. Sorry!

**Comment by JMartinez9820** [comment]
@pa1nki113r I've changed it to pb_staging, so it should safe to merge now.

**Comment by JMartinez9820** [comment]
List of changes from today to last month:
Today:
- SMG's Laser Sight returns! Now selectable via the weapon special wheel along with dual wield. Thanks Cemtex for the code.
- Demon Tech Trooper and Vicious Imp heads added.
- Demon Tech Rifle Respect, Reloads fixed.
Yesterday:
- Various tweaks and gore fixes to the Nazi.
- Nazi head shots fixed!

Several Days ago:
Belphegor gore additions:
- Head sprites, bottom torso and legs (sprites by keeper)
- Plasma death (Sprites by keeper)
- blown up gibs
- Horn pieces
- Blood fixes
Infernus gore additions:
- Blown up gib sprites
- blood fixes
- horn pieces
Nazi gore additions:
- new cut death (sprites by mryayayify)
Rocket Zombie:
- It's rocket should no longer go through other former humans and buffed slighty
- Mancubus arm no longer disappears.
- Deagle pickup changed
- Lost soul health decreased
- Plasma deaths on the Infernus, Belphegor and Afrit added.

I have more but it's quite a lot.

**Comment by JMartinez9820** [comment]
Changes made today on my branch:
- Tweaks to the SMG laser toggle switch
- Minigun and Plasma sound looping fixed
- Nazi fatalities have been added! There are two, thanks to Keeper and Mryayayify for the sprites.
- New Nazi death animations added.

**Comment by JMartinez9820** [comment]
Forgot one more:
- My branch is now based on PB_Staging, a development branch made to test new changes before getting merged to master.

**Comment by JMartinez9820** [comment]
My pull request is safe to merge, just in case it was missed.

**Comment by JMartinez9820** [comment]
@pa1nki113r Just in case you missed my pull request, I have tested everything and my pull request is safe to merge into Staging. If there are any issues DM me or ask me here.

**Comment by pa1nki113r** [comment]
Sorry I thought I merged this the other day, that's on me

**Pull request merged**
