### PR TITLE
Revert "Removed old acs scripts and old cvar stuff"

### PR DESCRIPTION
**Pull request by CharlesThobe**
This reverts commit 545b34b76f8149ca436d3e040e7ef822650b45b5.
This fixes a bug where shooting a hell knight causes a freeze and a memory leak.
only a draft for testing and reporting that reverting this commit fixes the bug, not meant for merging.
Will close it when a proper fix is implemented.

### CODE REVIEW

**Comment by JMartinez9820** [comment]
Is there a way to reproduce the memory leak? I'm thinking about modifying the pull request to remove anything related to the older cvars, because me and Kamil did quite a lot here.

**Comment by CharlesThobe** [comment]
Just spawn a hell knight and shoot it untill gzdoom freezes/displays a memory leak detection message

**Comment by CharlesThobe** [comment]
Rifles, ssg and auto shotgun and the submachine gun were tested.

**Comment by CharlesThobe** [comment]
for example the hell knight behind the red door in map05 in doom 2
```
skill 4

map map05

god

give all
```

**Comment by CharlesThobe** [comment]
Also the branch I'm testing against is JMBranch_Staging

**Comment by JMartinez9820** [comment]
Merging this as a fallback for now.

**Pull request merged**
