### PR TITLE
Fixed null crashes (Fixes Delta Touch)

### PR DESCRIPTION
**Pull request by emileb**

### CODE REVIEW

**Comment by pa1nki113r** [comment]
Fixed these on my end awhile back, still a good find. Will close PR.

**Comment by emileb** [comment]
I think these are different null checks than the ones from a few months ago, but are a similar problem (Script errors when running on non-JIT interpreter)

**Comment by JMartinez9820** [comment]
@emileb Even though your pull request is closed, I would recommend syncing it to the latest changes from master.

**Comment by emileb** [comment]
OK will do!

**Pull request closed without merging**
