### PR TITLE
Optimized all sprites again and removed tanks

### PR DESCRIPTION
**Pull request by DemonSlayer1997**

### CODE REVIEW

**Review by pa1nki113r — DISMISSED** [review]
Resolve the conflicts with master and I will approve

**Comment by DemonSlayer1997** [comment]
> Разрешите конфликты с мастером и я одобрю

Done :)

**Comment by DemonSlayer1997** [comment]
> Resolve the conflicts with master and I will approve

Done

**Comment by JMartinez9820** [comment]
@pa1nki113r I have helped Kamil resolve the conflicts with his branch. Should be safe to merge now.

**Review by pa1nki113r — APPROVED** [review]

**Pull request merged**
