### PR TITLE
A_GunFlash compatibility

### PR DESCRIPTION
**Pull request by popguy12**
adds A_GunFlash to a dummy Flash state for compatibility with mods that detect the Flash state, this currently only affects overhauled weapons, and i hope that PA1N includes A_GunFlash from now on for the remaining weapons

### CODE REVIEW

**Comment by pa1nki113r** [comment]
Small conflict with carbine

**Review by pa1nki113r — CHANGES_REQUESTED** [review]
Update the carbine file and we're good to go

**Comment by popguy12** [comment]
i saw the issue, slight difference in values on one line, i think that should fix it

**Review by popguy12 — COMMENTED** [review]
done

**Review by pa1nki113r — APPROVED** [review]

**Pull request merged**
