### PR TITLE
Flying physics for more dropped weapons

### PR DESCRIPTION
**Pull request by mryayayify**
As a bonus, I gave the QSG Zombie different sprites and will become the the "Sawed-Off Shotgun Zombie"

### CODE REVIEW

**Comment by JMartinez9820** [comment]
I want to report a serious major bug with the dropped weapons. When I was trying to test out the spawns, since the weapon spawns are based on the dropped actors, the weapons would infinitely spin out of control when they are spawned in the place of the weapon. For example, if the ASG replaces the Shotgun, the ASG sprite actually spins out of control. You also can not pick up the weapons. Did mess something up in the spawners? You might want to take a look at the weapon spawners or try to fix this error.
--

**Comment by JMartinez9820** [comment]
Repost:
I want to report a serious major bug with the dropped weapons. When I was trying to test out the spawns, since the weapon spawns are based on the dropped actors, the weapons would infinitely spin out of control when they are spawned in the place of the weapon. For example, if the ASG replaces the Shotgun, the ASG sprite actually spins out of control. You also can not pick up the weapons. Did mess something up in the spawners? You might want to take a look at the weapon spawners or try to fix this error.

**Comment by pa1nki113r** [comment]
Is this safe to merge? I'm seeing a lot of sprite files with changes too. What's up with that?

**Comment by JMartinez9820** [comment]
Well, Yify has converted the Quad Shotgun Zombie into a Super Shotgun Zombie in terms of the sprite changes, but he didn't delete the old files. In my opinion, this PR is not safe to merge due to serious bugs with the weapon spawners. The weapons would infinitely spin and can't be picked up if it's not dropped by an enemy. I might consider fixing the spawners to prevent this, or this PR can be closed.

**Comment by pa1nki113r** [comment]
Will tackle weapon physics on actors since I have a new system in place for that with the chainsaw zombie as an example.

**Comment by mryayayify** [comment]
Ummm.... when can/should I reopen a pull request?

**Pull request closed without merging**
