### PR TITLE
dual ssg sprites

### PR DESCRIPTION
**Pull request by iamcarrotmaster**
idk what happened but it changed some shotgunguy stuff, the only stuff i meant to change was the dual ssg. if you can select only the dual ssg stuff that would be great

### CODE REVIEW

**Comment by JMartinez9820** [comment]
Hey Carrot, make sure to sync your branch to the latest update of the master branch every time it updates. This is recommended to prevent issues such as steps forward steps back problems. I know it sounds rough but its a good practice. It's the same procedure as doing a pull request, but instead of merging into master, it's going to be merged into your branch instead.

**Comment by Epictyphlosion** [comment]
Very nice sprites!

**Comment by pa1nki113r** [comment]
Welp.

**Comment by pa1nki113r** [comment]
Probably should either update this pr or just close it outright.

**Pull request merged**
