### PR TITLE
Tweaked shotgun aiming sprites, DMR and Plasma Rifle fixes involving reload key, Carbine Zombie Grenade Throwing Animation Overhaul, stray pixel removal on Deagle and other changes

### PR DESCRIPTION
**Pull request by JMartinez9820**
The shotgun aiming sprites when about to aimed have been tweaked, thanks to ArtsyShyGuy for the sprites.
DMR: I have fixed a minor problem with dual wield DMRs showing the single DMR sprite when you press the reload key on full ammo, and I added deselect animation sprites for the dual wield DMR (I used the current kick frames as the base).
For the M1 Plasma Rifle, the "always reload" bug when you press the reload button on the dual-wield M1 Plasma Rifle has been resolved.
If there is a merge conflict, let me know.

Update 4/26/20: Updated the Carbine Zombie's grenade throwing animations to match with the other overhauled Zombies

Update 4/27/20: Stray pixels on the Deagle's Weapon Respect animation removed.

### CODE REVIEW

**Comment by JMartinez9820** [comment]
Reposting the updates to my pull request just in case anyone needs them.
Update 4/26/20: Updated the Carbine Zombie's grenade-throwing animations to match with the other overhauled Zombies. It looked weird for him to use the old animations in my opinion, because other overhauled Zombies had new animations.

Update 4/27/20: Stray pixels on the Deagle's Weapon Respect animation were removed.

**Comment by goldenmob72** [comment]
There a few stray pixels on the Carbine weapon respect (we already discussed this) and it will be updated too

**Comment by JMartinez9820** [comment]
Just in case anyone needs a changelog of all changes made during this pull request.
4/26/20: Updated the Carbine Zombie's grenade-throwing animations to match with the other overhauled Zombies
4/27/20: Stray pixels on the Deagle's Weapon Respect animation removed.
5/2/20: CyberBaron's burning and black hole deaths were fixed.
5/6/20: Fixed a major problem with dual pulse cannons not working due to a removed actor being called. Also fixed the recoil375 error on the pulse cannon alt-fire as that script has been removed.
5/10/20: 
- Added the iron sights sound to play when aim down the sights (zoomed) mode is going to be used.
- Chainsaw Weapon Special SSG sprites now match with the new SSG sprites, currently placeholders though.
- Stray pixels removed on Carbine Weapon Respect animation.
- Brightmaps for shotgun updated.
Today:
- Nerfed the buckshot and slug damage when aiming to be evenly matched with the standard hip-fire damage.
- Fixed the double axe drop when you shoot a lab guy in half when he does the jaw shot off suffering animation (this happens when you use the autoshotgun).

**Comment by JMartinez9820** [comment]
Updated changelog and repost of end of the earlier changelog:
5/10/20: Added the iron sights sound to play when aim down the sights (zoomed) mode is going to be used.
Chainsaw Weapon Special SSG sprites now match with the new SSG sprites, currently placeholders though. Stray pixels removed on Carbine Weapon Respect animation. Brightmaps for shotgun updated.
5/15/20: Nerfed the buckshot and slug damage when aiming (ADS alt-fire mode) to be evenly matched with the standard hip-fire damage. Fixed the double axe drop when you shoot a lab guy in half when he does the jaw shot off suffering animation (this happens when you use the autoshotgun).

**Comment by JMartinez9820** [comment]
Continued:
5/16/20: Finally fixed the highly requested crouch toggle feature. Fixed crouch toggle code from ZMovement 3.2.1, credit goes to IvoryDuke obviously
Yesterday: Fixed most or all of the ACS related error messages on the LMG, QSG, and Unmaker. Pulse Cannon and Chainsaw were fixed before. Fixed a minor with the Nailgun in Javelin "reloading" when the reload key is pressed with no ammo left in the reserve. NoAmmo state of the Nailgun now properly checks to see if ammo is in or not. I thought it looked weird to see it changed to the sprite with ammo to without. LMG Belt Mode now has a proper deselect animation, based on selection animation.

**Comment by JMartinez9820** [comment]
Closing pull request just in case of problems encountered from testing.

**Comment by JMartinez9820** [comment]
Everything seems to be working fine as is. Reopening pull request.

**Comment by JMartinez9820** [comment]
Due to a sync conflict, I will be closing my pull request until further notice.

**Pull request closed without merging**
