### PR TITLE
Fixed kicks resurrect bug / Infinite death fade

### PR DESCRIPTION
**Pull request by jaih1r0**
-Fixed the kicks not working after resurrecting due to the handler not taking "PlayerIsDead" item

-Fixed the slow Fade to Black 'infinite' fade bug

### CODE REVIEW

**Comment by generic-name-guy** [comment]
could you fix the arm staying after death too?

**Comment by jaih1r0** [comment]
well i've never encountered that bug (or at least never noticed it), but i think it should be easy to fix
i might check it

**Comment by jaih1r0** [comment]
> could you fix the arm staying after death too?

Done :D

**Comment by generic-name-guy** [comment]
hell yeah

**Pull request merged**
