### PR TITLE
Carbine Fire Controls Restored

### PR DESCRIPTION
**Pull request by cemtex-tk**
Carbine fire controls have been dummied out for a while so I have brought them back with some changes.

-Un-commented out the lines for the carbine in the file for the weapon wheel and changed the PNG locations to new ones of icons I made.
-Added back the weaponspecial check for the wheel on the carbine.
-Heavily modified the weapon special to my spec (new version I came up with that cleans up the selection actors using an overlay instead of jumping states).
-Three round burst will stop if you let go of the fire button, and also reset so that the next time you fire you can shoot all three rounds.
-Burst and semi use the same fire/fire2 states as before so no more one tic increase in FPS as previous.
-Completely removed the Fire2Semi and Fire2Burst states since they are not being used.
-Akimbo will always be full auto, and attempting to change the fire controls while in akimbo will just cancel and clear out (it will at least A_log to tell you what is happening).
-Added a carbine full auto actor to the players start items (will be useful for outside HUDs).
-Dummied out the option in menudef selecting fire controls or dual wielding.

If this one gets merged I can make the updates to HXRTC HUD.

### CODE REVIEW

**Comment by D3X1KAXYZ** [comment]
I guess this could feel op in more experienced hands, however, I don't find it OP. Kinda feels on par with the SMG. 
_(tested with DooM1 E1 and map01 of Plutonia on brutal difficulty with chaotic random (no overlord))_
_I wouldn't consider myself a great benchmark of what is OP for pb though._
**I approve of this being added back.**

**Comment by cemtex-tk** [comment]
The key difference was the previous instance of burst fire removes a tic between shots, giving it's OP-ness in game.  This burst uses exactly the same fire state as what is currently used, so at this point it is lateral of a choice and pretty much user preference only.

I mean I could write in a cvar to take out a tic if one were to like being OP on purpose.

**Comment by Dantido2** [comment]
Yes, please. The carbine fire modes were amazing, and I would like them to come back.

**Review by pa1nki113r — CHANGES_REQUESTED** [review]
MENUDEF conflict needs to be resolved

**Comment by cemtex-tk** [comment]
Sorry this took so long to get back to this.  I reviewed my changes and it
looks like it is good to go.

**Review by pa1nki113r — APPROVED** [review]

**Pull request merged**
