### PR TITLE
Crash fix and Weapon shell fixes/Modifications

### PR DESCRIPTION
**Pull request by ADoomedSpaceMarine**
There are three files modified in this update request. A couple visual issues, and a console breaking crash that kept PB3 from starting.

One fixes the MP40 ejection issues. This comment is from the initial commit and resolves these issues:

"Upon using the "give weapons" cheat to see what PB3 had to offer, once I had made it to the MP40 I found the shell ejection was broken. This was due to the fact that a right port ejection firearm was ejecting shells from the right side, but were falling to the left. This led to the ejection arc on both the vanilla and PB mode MP40's having shell ejection that arced over the firearm, as opposed to away from the right side of the receiver.  The fixes listed above also adjust the horizontal and vertical spawn offsets to better appear as if originating from the firearm." 

This change to the code has fixed the previously aesthetically distracting shell issue listed and chronicled above an produces this result:

Figure 1 - Before the fix (MP40)
MP40 Before Fix

Figure 2 - Modified and Fixed MP40
MP40 Shell fix

The Second fix in this request adds a shell ejection to the Desert Eagle's hip fire state (which was absent prior to this pull request), and shifts shell ejection to the right due to the nature of the Desert Eagle chamber. With a centered chamber like the Deagle's brass ejection depends on two things: the dominant hand of the shooter, and the ability to control the recoil. As the marine's Deagle sprite is right-hand-dominant, I updated the hip and aimed code to reflect this when the weapon is used. This results in the shells all ejecting properly, and there is a gif of the committed changes below, all comments are welcome, and either way, the shell ejection is fixed now on the hip fire state.

The two fixes on the Deagle fall into two categories: fixes, and added realism (the latter of which is freely debatable, and dependent on what  @pa1nki113r wishes for the project.) Below is a GIF of both committed changes, and one before the MP40 was fixed.

Figure 3: Desert Eagle Hipfire shell fix, with left ejection
Desert Eagle Shell upon Fire State

Figure 4: Same fix shifted right (Note right hand is the primary hand as above)
Deagle Shift and Shell fix

The third issue was due to a lack of a tic value in line 793 of the M2's code. I understand from some of the changes made on the master branch the MK2 Plasma Rifle is getting an overhaul on the reloading sprites. This lead to the console calling an error on line 794, since the sprite call before it had no terminating time value. This updates that so it's fixed. This will allow those who want to play the beta to even have the game start. Changes are reflected in pull request and code additions/deletions.

Figure 5: Problematic line
Plasma Error

Figure 5: Error tossed up due to lack of tic call on line 793
Plasma Error (Master)

Forgive the merges and revision junk. There's been a bit of learning curve today with GitHub, but overtime I'll grow into it. I wanted to rename the branch, so that's why you saw some of the mess, but anyway, the changes, regardless of type will be committed to this branch until further notice, or opportunity opens for a new branch to form. I just didn't want half a million branches causing confusion. 

As stated above, the Deagle's a matter of perspective. That code can be modified quit simply to shoot the shells right or left of the firearm. 

Also, for sake of simplicity, I will test on Zdoom, and commit changes from GitHub, versus Git for desktop.

### CODE REVIEW

**Comment by ADoomedSpaceMarine** [comment]
Closed to clean up and move to an existing branch.

**Comment by ADoomedSpaceMarine** [comment]
And crash resolved.

**Comment by votaguszuriy13** [comment]
Script warning, "Project_Brutality-master.pk3:actors/weapons/slot1/saw.dec" line 69:
Unknown class name 'UMGSelected' of type 'Inventory'
Script warning, "Project_Brutality-master.pk3:actors/weapons/slot3/shotgun.dec" line 957:
Numeric type expected, got "Auto"

Help me brother!

**Comment by votaguszuriy13** [comment]
Which program do you use to view these lines?

**Comment by ADoomedSpaceMarine** [comment]
So, this PR wasn't merged, and was closed. For the most recent build, try Painkiller's master repo. Within the master, the shell fixes were just merged this week and some of the bugs we were working on got fixed. This wasn't even the final Pull that ended up getting merged. If the issue persists on the master, let me know and I'll get together with a couple other devs on the team and see what we can do.

**Pull request closed without merging**
