### PR TITLE
A_CustomMissile Deprecation fix

### PR DESCRIPTION
**Pull request by JMartinez9820**
Changed the deprecated A_custommissile to A_SpawnProjectile on the overload cell explosion. Although it works, I would like others to test this out to see if the explosions work properly or not.

### CODE REVIEW

**Comment by vidaritos** [comment]
If I type `summon EmptyCellOL` the casing appears and creates a thick smoke and then explodes, but I can't find any references to it in the code beyond its definition. Is it supposed to be a replacement for all empty railgun casings or a random occurance? How does it appear during normal gameplay @cemtex-tk ?

**Comment by JMartinez9820** [comment]
Random occurrence when the Overloaded cell cvar is on, usually after fully charging laser mode.

**Comment by vidaritos** [comment]
Ah, enabled it now and...yeah it works 💥

If you feel really brave, you could do a global search and replace the function name in all 184 files ;)

**Comment by JMartinez9820** [comment]
Eh, not worth it tbh. I'm not going to risk messing up anything because I tend to rush things. You can help me out if you want by submitting a PR to my branch.

**Comment by cemtex-tk** [comment]
It is not a replacement in any way to an empty cell.  You should find the
actor in the casings.txt if I remember correctly, next to the emptycell.
The actor is used when you fire the railgun in laser mode, and perform a
full 60 cell blast from the railgun (and even then should be a 50%
occurance rate if I remember correctly).  Then and only then is that actor
used.

**Review by pa1nki113r — APPROVED** [review]

**Pull request merged**
