### PR TITLE
Headshot fix on Volcabus and BarrelKaboom actor tweak

### PR DESCRIPTION
**Pull request by JMartinez9820**
- Nerfed Headshot damage on Volcabus so it takes longer to kill a Volcabus with headshots.
- BarrelKaboom effect restored to how it once was originally (based on PB 3.0 test 2018 and various prs that involved the barrels).

### CODE REVIEW

**Comment by generic-name-guy** [comment]
can you add screenshots of the barrelkaboom thing

**Comment by JMartinez9820** [comment]
Code or how it looked like in game

**Comment by generic-name-guy** [comment]
in game

**Comment by JMartinez9820** [comment]
Screenshot_Doom_20240122_221612
Screenshot_Doom_20240122_221654

**Comment by JMartinez9820** [comment]
in game

**Comment by JMartinez9820** [comment]
iirc this is how the barrel explosion looked before it was changed

**Comment by popguy12** [comment]
i always thought the explosion clouds flying out and up looked goofy as hell
we should probably see about just making a better effect anyways

**Comment by JMartinez9820** [comment]
Volcabus headshot is split off to pr #1227

**Pull request closed without merging**
