### PR TITLE
axe slidekick fix, dying helmet zombieman no arm fix, qsg zombie legblewed change, and pinned zombieman fix

### PR DESCRIPTION
**Pull request by funnymanDELUXE**
ignore the other slidekick fix, i forgot to compare the actual fix branch just in case

anyways, all this does is change the offsets from within the dec to get rid of the weird jittery movement while slidekicking with the axe

update: added a dyinghelmetzombiemannoarm fix too, the sprite conflict is resolved so he wont disappear when in that state anymore

update again: shooting the quad shotgun guys leg off doesnt properly have the headshot brutality bonus, so i replaced the actor spawned when shooting his leg off to the legblewed variant

another update: fixed a bug where having the zombieman pinned against the wall wouldnt spawn in the first place. a single underscore was needed lol

### CODE REVIEW

**Comment by pa1nki113r** [comment]
We got conflicts on that one file mentioned above. Pull those changes into your local. Also, for some reason, monster offsets for some animations are reset to 0,0. Not sure if that's from my end or someone else's.

**Comment by funnymanDELUXE** [comment]
just pulled the changes and applied the fix again, should be mergeable without conflict now

**Comment by pa1nki113r** [comment]
Awesome, and you tested just to verify? Just making sure we don't get startup errors when we boot up the mod.

**Comment by funnymanDELUXE** [comment]
yup, should be all good

**Comment by pa1nki113r** [comment]
Uh oh, looks like my last master push is conflicting with this one file, pull the changes and give it a check?

**Comment by funnymanDELUXE** [comment]
yeah, the dyingnewguys dec was in conflict, i fixed it now though with the sprite conflict fix. dont mind the mass deletion stuff it was just a copy paste job lol

**Pull request merged**
