### PR TITLE
Legs, Ledge Grab, and Blood Splash improvements

### PR DESCRIPTION
**Pull request by Mechanical-sanity**
- Made it so that legs are not affected by any weapon offsets
- Legs will not disappear when kicking
- Ledge Grab activates no matter what. A jumpifinventory for every line is no longer required. Code is in the baseweapon file
- Added an option for a blood splash system of my own design. It emulates BDv18 blood splashes

(sorry for all the weird stuff going on in the github if you noticed it. I didn't know what I was doing)

### CODE REVIEW

**Comment by popguy12** [comment]
what exactly do you mean by "ledge grab activates no matter what"?

**Comment by Mechanical-sanity** [comment]
> what exactly do you mean by "ledge grab activates no matter what"?

I mean that because it is constantly checking in an infinite cycle, it will always go into the ledge grab state when you get the ledge grab token. I put the code in the base weapon, right under the ledge grab state so you should check it out.

**Comment by Mechanical-sanity** [comment]
I commented out the ledge grab checker from Zscript so that nothing will interrupt the new ledge grab code

**Comment by popguy12** [comment]
alright, Ledge grabbing seems fine, screen splash effects work fine, but the actual graphics for them will have to be looked at.
Whatever you did with the legs broke player color translations, so that will have to be looked into

**Comment by Mechanical-sanity** [comment]
> alright, Ledge grabbing seems fine, screen splash effects work fine, but the actual graphics for them will have to be looked at.
> Whatever you did with the legs broke player color translations, so that will have to be looked into

I might've misspelled something. I'll have to check to see for the color translations. It's probably found in that one overlyoffset line

**Comment by popguy12** [comment]
aight, stuff has been fixed up, this PR is ready for the next time PA1N looks at the PRs

**Comment by Mechanical-sanity** [comment]
This needs more work. I'm closing this for now

**Pull request closed without merging**
