### PR TITLE
All brightmap images optimized to decrease file size

### PR DESCRIPTION
**Pull request by DemonSlayer1997**
All brightmaps have been optimized to decrease the file size of the mod by a minimal margin

### CODE REVIEW

**Comment by pa1nki113r** [comment]
Ok lets take a second here, that is a lot of files being modified. Are you absolutely SURE this is safe to merge into master?

**Comment by DemonSlayer1997** [comment]
You're right. If it comes to a huge number of files, then I will gradually make changes. The Brigtmaps folder is fine. I am testing the build for stability before submitting to GitHub :)

**Comment by pa1nki113r** [comment]
Lets resolve this conflicts then I'll merge it

**Comment by DemonSlayer1997** [comment]
I have fixed the merge conflicts with the help from JMartinez. This should be safe to merge now.

**Pull request closed without merging**
